{
}
const products = [
  {
    id: 1,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "3.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 2,
    name: "ADIDAS 4DFWD X PARLEY2 ",
    price: 125,
    discountPrice: "",
    image: "63.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8,  10, 11],
  },
  {
    id: 3,
    name: "ADIDAS 4DFWD X PARLEY3 ",
    price: 125,
    discountPrice: "",
    image: "6.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [ 9, 10, 11],
  },
  {
    id: 4,
    name: "ADIDAS 4DFWD X PARLEY4 ",
    price: 125,
    discountPrice: "",
    image: "7.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 11, 12, 13],
  },
  {
    id: 5,
    name: "ADIDAS 4DFWD X PARLEY5 ",
    price: 125,
    discountPrice: "",
    image: "8.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 6,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "9.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 7,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "10.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 8,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "12.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 9,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "13.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 10,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "14.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 11,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "15.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 12,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "16.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 13,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "17.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 14,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "18.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 15,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "20.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 16,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "22.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 17,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "25.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 18,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "26.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 19,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "27.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
  {
    id: 20,
    name: "ADIDAS 4DFWD X PARLEY ",
    price: 125,
    discountPrice: "",
    image: "30.jpg",
    category: "",
    description: "Men's Road Running Shoes Enamel Blue/ University White",
    colors: ["#000", "#BDBDBD", "#F08155"],
    sizes: [7, 8, 9, 10, 11],
  },
];

const reviews = [
  {
    id: 1,
    title: "Good Quality",
    review: "I highly recommend shopping from kicks",
    rating: 5,
    pdtImage: "21.jpg",
    profileImage: "0.jpg",
  },
  {
    id: 2,
    title: "Good Quality",
    review: "I highly recommend shopping from kicks",
    rating: 5,
    pdtImage: "67.jpg",
    profileImage: "48.jpg",
  },
  {
    id: 3,
    title: "Good Quality",
    review: "I highly recommend shopping from kicks",
    rating: 5,
    pdtImage: "11.jpg",
    profileImage: "61.jpg",
  },
];

const categories = [
  {
    id: 1,
    catItemName: "Runners",
    image: "72.jpg",
  },
  {
    id: 2,
    catItemName: "Sneakers",
    image: "6.jpg",
  },
  {
    id: 3,
    catItemName: "Basketball",
    image: "58.jpg",
  },
  {
    id: 4,
    catItemName: "Outdoor",
    image: "69.jpg",
  },
  {
    id: 5,
    catItemName: "Golf",
    image: "39.jpg",
  },
  {
    id: 6,
    catItemName: "Hiking",
    image: "26.jpg",
  },
];

export default products;
export { reviews, categories };
